export enum WebsiteName {
  TWITTER = 'TWITTER',
  DERPIBOORU = 'DERPIBOORU',
  DEVIANTART = 'DEVIANTART',
  PINTEREST = 'PINTEREST',
  FURAFFINITY = 'FURAFFINITY',
  INSTAGRAM = 'INSTAGRAM',
  FIVERR = 'FIVERR',
  DISCORD = 'DISCORD',
  PATREON = 'PATREON',
  YCHCOMMISHES = 'YCHCOMMISHES',
}
